describe('Calculator prototype test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')//select build
        cy.get('[data-testid="number1Field"]').type('2')//Get first number type
        cy.get('[data-testid="number2Field"]').type('5')//get second number type
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')//get operation 1 or 'Subtract
        cy.get('[data-testid="calculateButton"]').click()//get calculate mygtukas ir click
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')//get answer ir should have value
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })
    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('Prototype')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })

})


describe('Calculator Build 1 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })
    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('1')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 2 test', () => {
    it('Add 2+5=7', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('2')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 3 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 4 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('4')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 5 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('5')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 6 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('6')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 7 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('7')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 8 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('8')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})

describe('Calculator Build 9 test', () => {
    it('Add 2+5=7', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('2')
        cy.get('[data-testid="number2Field"]').type('5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '7')
    })

    it('Add 1,11+3=4,11', () => { //fail
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('1,11')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '4,11')
    })

    it('Add 17.3+0.8=18.1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('17.3')
        cy.get('[data-testid="number2Field"]').type('0.8')
        cy.get('[data-testid="selectOperationDropdown"]').select('Add')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '18.1')
    })

    it('Subtract 279-49=230', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('279')
        cy.get('[data-testid="number2Field"]').type('49')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '230')
    })

    it('Subtract 2900-34899=-31999', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('2900')
        cy.get('[data-testid="number2Field"]').type('34899')
        cy.get('[data-testid="selectOperationDropdown"]').select('Subtract')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-31999')
    })

    it('Multiply 58*999=57942', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('58')
        cy.get('[data-testid="number2Field"]').type('999')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '57942')
    })

    it('Multiply -29*3=-87', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-87')
    })

    it('Multiply 2.5*2.5=6.25', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('2.5')
        cy.get('[data-testid="number2Field"]').type('2.5')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '6.25')
    })

    it('Multiply 9084*0=0', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('9084')
        cy.get('[data-testid="number2Field"]').type('0')
        cy.get('[data-testid="selectOperationDropdown"]').select('Multiply')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0')
    })

    it('Divide 904567/123456789=0.0073269927666756345', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('904567')
        cy.get('[data-testid="number2Field"]').type('123456789')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .invoke('val')
            .should('match', /^0\.00732\d+$/)
    })

    it('Divide 0.111/0.111=1', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('0.111')
        cy.get('[data-testid="number2Field"]').type('0.111')
        cy.get('[data-testid="selectOperationDropdown"]').select('Divide')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '1')
    })

    it('Concatenate 23 and 20', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('23')
        cy.get('[data-testid="number2Field"]').type('20')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '2320')
    })

    it('Concatenate 0.34 and 2', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('0.34')
        cy.get('[data-testid="number2Field"]').type('2')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '0.342')
    })

    it('Concatenate -29 and 3', () => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.get('[data-testid="selectBuild"]').select('9')
        cy.get('[data-testid="number1Field"]').type('-29')
        cy.get('[data-testid="number2Field"]').type('3')
        cy.get('[data-testid="selectOperationDropdown"]').select('Concatenate')
        cy.get('[data-testid="calculateButton"]').click()
        cy.get('[data-testid="numberAnswerField"]')
            .should('have.value', '-293')
    })
})
